version: "4"
services:
  mysql-db:
    container_name: order-service-mysql-db
    image: mysql:latest
    restart: always
#    set password mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
